modLoader="neoforge"
loaderVersion="[21.11.30-beta, )"
license="${mod_license}"
issueTrackerURL="https://github.com/miitong/Eliminate/issues"
showAsResourcePack=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
name="${mod_name}"
description="Vertical Chunk Culling for performance optimization."
authors=["GZ_Sakura", "leemwood"]
displayURL="https://modrinth.com/mod/eliminate"
icon="assets/eliminate/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="[21.11.30-beta, )"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory=false
versionRange="[15.0.127, )"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="modmenu"
mandatory=false
versionRange="[11.0.1, )"
ordering="NONE"
side="CLIENT"
